spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:sqlserver://salted.database.windows.net:1433
#    url: jdbc:mysql://localhost:3306/salted26
    username: salted
    password: gksmfdlA!01

# MyBatis ?? ??
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
